@startuml

[*] --> 停止 : 起動

停止 -> 稼働中 : Start
稼働中 -> 停止 : Stop

停止 --> [*] : Exit

state 稼働中{

    [*] --> 初期化
    初期化 --> 注文確認 : 初期化完了

    初期化 : entry / 変数リセット
    初期化 : entry / 取引通貨設定
    初期化 : entry / 目標初期化
    
    注文確認 --> 市場分析
    注文確認 --> 注文削除 : when(timedelta>保持閾値)
    注文確認 --> UI更新 : Error / Cooling

    注文確認 : entry / サーバー時間取得
    注文確認 : do / 注文状況と経過時間確認

    注文削除 --> 市場分析

    市場分析 --> 買い注文 : when(判定値>買い閾値)
    市場分析 --> 売り注文 : when(判定値>売り閾値)
    市場分析 --> UI更新

    買い注文 --> UI更新
    売り注文 --> UI更新

    UI更新 --> LINE送信 : when(timedelta>設定時間)

    UI更新 --> CSV出力 : when(timedelta>設定時間)
    LINE送信 --> CSV出力 : when(timedelta>設定時間)

    UI更新 --> 待機中
    LINE送信 --> 待機中
    CSV出力 --> 待機中

    待機中 --> 注文確認

}



@enduml